name: Build Windows Native Exe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GraalVM Community
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.0.2'
          distribution: 'graalvm-community'
          java-version: '21'

      - name: Build JAR
        run: mvn package -DskipTests "-Dexec.skip=true"
        shell: cmd

      - name: Build Native Image
        run: |
          native-image -cp target/xshell-session-to-tabby.jar -H:Name=xshell-session-to-tabby --no-fallback -H:ConfigurationFileDirectories=src/main/resources/native/agent-output com.coffee.Main
        shell: cmd

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: xshell-session-to-tabby-exe
          path: xshell-session-to-tabby.exe
